"""empty message

Revision ID: 52880a84ac00
Revises: 4ec079bfae56
Create Date: 2020-04-26 23:47:45.488146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52880a84ac00'
down_revision = '4ec079bfae56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('list', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('list', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
